### ISSUE TITLE
Getting this Error intermittenly

### ISSUE THREAD

**Issue by JonathanEdMoore** [makeasnek/FindTheMag2#35]
Traceback (most recent call last):
  File "C:\Users\jmjon\FindTheMag2-3.0\main.py", line 4602, in <module>
    boinc_loop(False, rpc_client)
  File "C:\Users\jmjon\FindTheMag2-3.0\main.py", line 3545, in boinc_loop
    ) = generate_stats(
        ^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\FindTheMag2-3.0\main.py", line 2189, in generate_stats
    combined_stats, unapproved_projects = add_mag_to_combined_stats(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\FindTheMag2-3.0\main.py", line 1618, in add_mag_to_combined_stats
    found_mag_ratio = mag_ratios.get(project_url)
                      ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by makeasnek** [comment]
Hey just to check are you on the absolutely latest version of the code?

**Comment by makeasnek** [comment]
If you can please change your debug level to DEBUG in your user_config.py file and send it to makeasnek{at}gmail.com after this happens again, I can look into it. Thanks!

**Comment by makeasnek** [comment]
Thank you for sending over the debug log. Looking at this, the root of the problem is that the script is having trouble connecting to Gridcoinstats, perhaps the site was down for maintenance. However, it _should_ handle this error more gracefully. I'll get a patch together for this soon but in the meantime, if you run the Gridcoin wallet on your machine that should prevent from re-occuring :). I'll leave this issue open until I have a patch.

**Comment by JonathanEdMoore** [comment]
I see. Yeah, I run my wallet on a different machine (which explains why that machine never crashes). Thanks for looking into this.
