### ISSUE TITLE
Overestimation of credit/hr for milkyway

### ISSUE THREAD

**Issue by KaiserRoll42069** [makeasnek/FindTheMag2#47]
FindTheMag2 miscalculates the credit/hr and therefore efficiency of multi-threaded tasks that 'hide' their threads under one executable, such as MilkyWay@home. 

![Screenshot 2024-03-07 204929](https://github.com/makeasnek/FindTheMag2/assets/76792753/a1b57526-a957-4d40-bd8d-54693bdf9efa)
![Screenshot 2024-03-07 204906](https://github.com/makeasnek/FindTheMag2/assets/76792753/951274df-c351-4162-a275-a3e0a36207eb)
![Screenshot 2024-03-07 205543](https://github.com/makeasnek/FindTheMag2/assets/76792753/c644c79c-7a90-484c-8fe8-ac0a68bdd30e)

MilkyWay is actually using 4 or 5 threads, despite showing up as 1 task in BOINC. This results in CPU time being 4-5 times higher than wall time. It appears that credit/hr is calculated using wall time and not CPU time, but this results in MilkyWay being rewarded 4-5 times the credit/hr compared to projects that divide each thread into individual tasks.

**Comment by KaiserRoll42069** [comment]
I don't really know anything about coding but I think a possible fix could be using CPU time instead of wall time if CPU time is higher.

**Comment by makeasnek** [comment]
Thank you for the bug report, this is fine imo. The goal of FTM is to calculate "Given one hour of time, what is the most efficient project to crunch using my hardware?". It doesn't care if your hardware has one core or cores, whether it uses CPU or GPU, etc. The wall time is how long it took your computer to finish a workunit, regardless of what hardware resources are utilized. CPU time would also work, except that it doesn't account for GPU workunits since it will make them appear to take basically no time at all.
