### ISSUE TITLE
Won't Get New Tasks

### ISSUE THREAD

**Issue by JonathanEdMoore** [makeasnek/FindTheMag2#5]
When I run the program, I keeps seeing this status for all of my projects and BOINC is not adding any new tasks to crunch. What's going on here?

<img width="144" alt="Screenshot 2023-02-05 at 9 48 23 AM" src="https://user-images.githubusercontent.com/48260787/216826478-de3f7675-df71-4294-9296-3c14996d3c11.png">

**Comment by makeasnek** [comment]
This is how FTM works, it "no new tasks" all projects except for what it determines to be the "highest priority project". Highest priority project is the project most behind it's "expected time" based on project weights. The way FTM is written, you should never run out of tasks, please re-open a new issue if that does happen though!

**Comment by makeasnek** [comment]
Thank you for this issue though, I realize I didn't document this in the readme

**Comment by makeasnek** [comment]
And also just to clarify, when running FTM, BOINC has no tasks listed under tasks? It's just empty? And all projects are set to "no new tasks?"

**Comment by JonathanEdMoore** [comment]
> And also just to clarify, when running FTM, BOINC has no tasks listed under tasks? It's just empty? And all projects are set to "no new tasks?"

Yes, that's correct. There are no tasks and all projects are set to "no new tasks".

**Comment by JonathanEdMoore** [comment]
I'm seeing this issue again, only this time all the projects are showing "Won't Get New Tasks". I sent an email last night with my debug.log and config.py file.

**Comment by makeasnek** [comment]
Thank you, I will look into this further. Can you also check for me, do you have some stalled downloads in transfers? I've been noticing on some of my rigs with stalled Rosetta uploads/downloads that this bug is occurring and am working on a fix.

**Comment by JonathanEdMoore** [comment]
Thanks!

No stalled downloads in transfers.

-Jonathan

**Comment by makeasnek** [comment]
Alrightey I have added some additional debug lines to the code to help figure out what's going on. The core issue (I think) is that FTM is thinking projects need to be "backed off" erroneously. 

You can see this in the log in the form of (for example): "DEBUG:root:Skipping project {'https://project.com/'} due to backoff period...". The question is _why_ it's marking these projects as needing the backoff.

Can you please:

1. Cancel any running FTM instances
2. Delete stats.json
3. Download new main.py from the repo
4. Run and send the log

**Comment by JonathanEdMoore** [comment]
Here is the new debug.log￼

**Comment by makeasnek** [comment]
Looks like the debug.log didn't make it across to my e-mail can you re-send?

**Comment by JonathanEdMoore** [comment]
Let me know if you got it.￼

**Comment by makeasnek** [comment]
Got it thank you! I should have an update for you (and hopefully a fix!) sometime tomorrow. Thank you again for all your debugging help!

**Comment by makeasnek** [comment]
Alright I believe I have finally fixed this, the issue is that FTM was interpreting the message "project requested delay of x seconds" to mean "we are out of work, don't keep requesting" so it was adding a backoff timer to those projects which doubled each time it got that message. Turns out projects include that message _every_ time work is requested, even if they deliver work! And the times are small enough (12-120 seconds) that there's no need to keep track of them separately, since FTM doesn't request that often anyways.

Can you please:

1.     Cancel any running FTM instances
2.     Delete stats.json and debug.log
3.     Download new main.py from the repo
4.     Run and send the log if issue persists

**Comment by JonathanEdMoore** [comment]
So far so good. It seems to be working. I’ll let you know if I run into any other issues.

Thanks for all the work! This is a cool tool!

-Jonathan

**Comment by makeasnek** [comment]
Just checking in to make sure this issue finally went away with the most recent patch. It did on my rigs but maybe yours have a different cause. Let me know if it didn't :).
