### ISSUE TITLE
Won't get new tasks (follow-up)

### ISSUE THREAD

**Issue by JonathanEdMoore** [makeasnek/FindTheMag2#6]
Following up on[ this issue](https://github.com/makeasnek/FindTheMag2/issues/5). I'm still not receiving any new tasks. Also, All of my projects are showing "Won't get new tasks". There isn't a single project getting new tasks.

**Comment by makeasnek** [comment]
That is strange, thank you for bringing this to my attention. In config.py can you please change the log level to "debug", re-run for 5 minutes, and send the debug.log file to makeasnek at gmail dot com?

**Comment by makeasnek** [comment]
And also please send along a copy of your config.py as well

**Comment by JonathanEdMoore** [comment]
Sent

**Comment by makeasnek** [comment]
Thank you! I have actually now another machine that is having this same problem and am working to debug it. From your log, FTM is currently not requesting new tasks because each project has a "backoff period" so we don't request tasks too often. FTM determined there was no work for some reason for all these projects and subsequently isn't interested in requesting any more for a while, but what I need to figure out is _why_ it determined that in the first place.

Can you try:

1. Close script
2. Download new main.py from this repo (added addl debug lines)
3. Delete stats.json file
4. Run script

And let me know if issue persists (send new debug.log if so). Thank you for helping me to debug this!

**Comment by makeasnek** [comment]
I've updated main.py with a fix I hope will work. It seems FTM was using a URL with incorrect capitalization and BOINC was rejecting it. Lmk if this fixes it for you.

**Comment by JonathanEdMoore** [comment]
It seems to be working now. I'll let you know if I run into any more issues.

**Comment by makeasnek** [comment]
Yay thank you!
